<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="hydws72702" ignored="0" name="retryCases" tests="5" failures="1" timestamp="06 Mar 2019 05:45:41 GMT" time="32.778" errors="0">
  <testcase name="test_1" time="0.018" classname="retryLogic.MyCases"/>
  <testcase name="test_2" time="0.067" classname="retryLogic.MyCases">
    <skipped/>
  </testcase> <!-- test_2 -->
  <testcase name="test_2" time="0.053" classname="retryLogic.MyCases">
    <skipped/>
  </testcase> <!-- test_2 -->
  <testcase name="test_2" time="0.053" classname="retryLogic.MyCases">
    <skipped/>
  </testcase> <!-- test_2 -->
  <testcase name="test_2" time="0.065" classname="retryLogic.MyCases">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at retryLogic.MyCases.test_2(MyCases.java:41)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test_2 -->
</testsuite> <!-- retryCases -->
